### ISSUE TITLE
if Rulers (Ctrl+R) - ON. - movement in X,Y is wrong

### ISSUE THREAD

**Issue by Evgenw** [chuanqisun/figma-plugin-spacemouse#12]
if Rulers (Ctrl+R) - ON. - movement in X,Y is wrong. For example, if I press to the right, the space shifts down-to the right, approximately an angle of 45.
Thanks :)

**Comment by chuanqisun** [comment]
Confirmed! I've been puzzled by this for a long time and thought something is broken with my setup, so thank you for digging up the root cause.

It turns out Figma [viewport API](https://www.figma.com/plugin-docs/api/figma-viewport) does not handle the ruler correctly. It will drift. I'm filing a bug towards Figma API.

UPDATE, issue tracked on Figma developer forum: https://forum.figma.com/t/viewport-center-is-inaccurate-when-ruler-is-on/34757

**Comment by chuanqisun** [comment]
Good news @Evgenw. This is fixed by the Figma development team.

**Comment by Evgenw** [comment]
Thank you so much!
