### ISSUE TITLE
Compatibility with Figma app 108.1

### ISSUE THREAD

**Issue by matzzee** [chuanqisun/figma-plugin-spacemouse#9]
Hey, thanks for the helpful plugin!

It was working fine before i updated to figma app version 108.1 on Win10
(don't know exactly which app version i used before. I sometimes skip an update...)
Now, the control by the SpaceMouse is just stuttering - not useable.

Thanks for your effort!

**Comment by brianpeiris** [comment]
I believe this is a bug in Chromium itself, and presumably the Figma app uses Electron or Chromium as its engine. 
I used puppeteer to test older versions of Chromium to confirm. Chromium 91 (puppeteer@9) does not exhibit any stuttering on the gamepad, but newer versions show glitching, where the gamepad axes values sometimes seem to return to zero incorrectly. I tested and confirmed the issue in Chromium 93, puppeteer@10, and above using this to test the gamepad values: https://greggman.github.io/html5-gamepad-test/
I happen to be using an old SpaceNavigator model, but I don't think that's the issue, since it works fine with the 3Dconnexion software.

**Comment by chuanqisun** [comment]
Thank you @brianpeiris  for the investigation. In theory, as Figma bumps up its Electron version, this issue could go away. Did you happen to test it in Chromium 102+

**Comment by brianpeiris** [comment]
Yes, puppeteer@14 uses Chromium 103 and it still has the same issue. You may have to file a report on Chromium's bugtracker, or get 3Dconnexion to bring it to Chromium's attention.

**Comment by chuanqisun** [comment]
Based on my latest testing with v116, I believe this issue has disappeared. Please let me know if it still happens. Happy to revisit.

**Comment by matzzee** [comment]
Hi,

unfortunately, i can't confirm from my side: It's still stuttering and not useable (unchanged). Figma is at 116.4.4, 3DConnexion is 3DxWare64_v10-8-10_r3503
